version: '3.8'

services:
  nextjs-test:
    container_name: nextjs_dev
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
